{ pkgs }:
# The spago-packages.nix file is generated by running
# 'spago2nix generate` in the backend directory.
let spagoPkgs = import ./spago-packages.nix { inherit pkgs; };
in pkgs.stdenv.mkDerivation {
  name = "backend";
  buildInputs = [
    spagoPkgs.installSpagoStyle
    spagoPkgs.buildSpagoStyle
  ];
  nativeBuildInputs = [
    pkgs.esbuild
    pkgs.purs
  ];
  src = ./.;
  # Install spago dependencies from spago-packages.nix
  unpackPhase = ''
    cp $src/spago.dhall .
    cp $src/packages.dhall .
    cp -r $src/src .
    install-spago-style
  '';
  # Build and bundle the backend.
  buildPhase = ''
    build-spago-style "./src/**/*.purs"
    echo 'import {main} from "./output/Main/index.js"; main();' | esbuild --platform=node --format=iife --bundle  --outfile="backend.js"
  '';
  installPhase = ''
    mkdir $out
    mv backend.js $out/
  '';
}
